ARCH=x86
PREFIX=/usr/local
LIB=posix
CC=gcc
CXX=g++
AR=ar
CROSS=
BINSUF=
LIBSUF=.so
FLAG=

ifeq ($(ARCH), x64)
FLAG+=-m64
else ifeq ($(ARCH), x86)
FLAG+=-m32
endif

ifeq ($(LIB), posix)
LINKFLAG+=-ldl
endif