#include "callf.h"

void* callfv(void* proc, unsigned long cnt, void** params) {
	void* ret;
	__asm__ volatile (
		"movq %2, %%rcx;"
		"cmpq $6, %%rcx;"
		"jle callf_less_than_6;"
		"subq $6, %%rcx;"
		"movq %3, %%rdx;"
		"movq %%rcx, %%rax;"
		"decq %%rax;"
		"shlq $3, %%rax;"
		"addq %%rax, %%rdx;"
		"addq $48, %%rdx;"
		"callf_loop:"
		"pushq (%%rdx);"
		"subq $8, %%rdx;"
		"loop callf_loop;"
		"callf_less_than_6:"
		"movq %2, %%rax;"
		"cmpq $6, %%rax;"
		"je callf_6;"
		"cmpq $5, %%rax;"
		"je callf_5;"
		"cmpq $4, %%rax;"
		"je callf_4;"
		"cmpq $3, %%rax;"
		"je callf_3;"
		"cmpq $2, %%rax;"
		"je callf_2;"
		"cmpq $1, %%rax;"
		"je callf_1;"
		"jmp callf_0;"
		"callf_6:"
		"movq %3, %%rax;"
		"addq $40, %%rax;"
		"movq (%%rax), %%r9;"
		"callf_5:"
		"movq %3, %%rax;"
		"addq $32, %%rax;"
		"movq (%%rax), %%r8;"
		"callf_4:"
		"movq %3, %%rax;"
		"addq $24, %%rax;"
		"movq (%%rax), %%rcx;"
		"callf_3:"
		"movq %3, %%rax;"
		"addq $16, %%rax;"
		"movq (%%rax), %%rdx;"
		"callf_2:"
		"movq %3, %%rax;"
		"addq $8, %%rax;"
		"movq (%%rax), %%rsi;"
		"callf_1:"
		"movq %3, %%rax;"
		"movq (%%rax), %%rdi;"
		"callf_0:"
		"movq %1, %%rax;"
		"call *%%rax;"
		"movq %%rax, %0;"
		"movq %2, %%rax;"
		"subq $48, %%rax;"
		"cmpq $0, %%rax;"
		"jle callf_end;"
		"shlq $3, %%rax;"
		"addq %%rax, %%rsp;"
		"callf_end:"
		: "=m" (ret)
		: "m" (proc), "m" (cnt), "m" (params)
		: "%rax", "%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"
	);
	return ret;
}